# Builds and pushes a new version of unstoppabledomains/zilliqa-dev-node image

name: Build & Push Zilliqa Dev Node

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag'
        default: 'v0.0.0'
        required: true

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider:
            ${{ secrets.WORKLOAD_ID_PROVIDER_PRODUCTION }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker with Google Artifact Registry
        id: push_to_registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            us-central1-docker.pkg.dev/unstoppable-domains/zilliqa/zilliqa-dev-node:${{ github.event.inputs.tag }}
            us-central1-docker.pkg.dev/unstoppable-domains/zilliqa/zilliqa-dev-node:latest
          context: ./docker/build

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create GitHub Release
        uses: zendesk/action-create-release@v1
        id: release
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
